site_name: Robert Strube's 2nd Brain
theme:
  name: material
  palette: 
    scheme: slate
    primary: indigo
    accent: indigo
  features:
  - navigation.instant
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - content.code.copy
  - content.code.annotate
  - toc.follow
  - toc.integrate
  icon:
    tag:
      default: material/tag
      apt: octicons/package-16
      arch-linux: simple/archlinux
      azure: material/microsoft-azure
      cheat-sheet: fontawesome/regular/lightbulb
      csharp: material/language-csharp
      code-example: material/file-code
      dd: fontawesome/solid/floppy-disk
      development: material/code-json
      dns: material/dns
      docker: simple/docker
      dotnet: material/dot-net
      electron: simple/electron
      external: octicons/link-external-16
      git: simple/git
      javascript: simple/javascript
      kde: material/monitor
      kvm-qemu: simple/qemu
      linux: material/linux
      lodash: simple/lodash
      react: material/react
      sbc: material/integrated-circuit-chip
      shell: material/code-greater-than
      sql-server: fontawesome/solid/database
      systemd: fontawesome/solid/gear
      tar: material/zip-box
      vim: simple/vimeo
      virtualization: octicons/container-16
      wayland: octicons/screen-full-16
      webpack: simple/webpack
      windows: simple/windows11
extra:
  tags:
    apt: apt
    arch linux: arch-linux
    azure: azure
    cheat sheet: cheat-sheet
    csharp: csharp
    code example: code-example
    dd: dd
    development: development
    dns: dns
    docker: docker
    dotnet: dotnet
    electron: electron
    external: external
    git: git
    javascript: javascript
    kde: kde
    kvm qemu: kvm-qemu
    linux: linux
    lodash: lodash
    react: react
    sbc: sbc
    shell: shell
    sql server: sql-server
    systemd: systemd
    tar: tar
    vim: vim
    virtualization: virtualization
    wayland: wayland
    webpack: webpack
    windows: windows
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - tags:
      tags_file: tags.md
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - roamlinks
  - awesome-pages
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde